version: 2.1
orbs:
  python: circleci/python@1.2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          command: |
            python -m venv venv
            cd venv/Scripts
            activate.bat  
            pip install --upgrade pip --user
      - run:
          command: |
            pip install -r requirements.txt    
      - run:
          name: Run django tests
          command: |
            python3 manage.py test

      - store_artifacts:
          path: test-results/
          destination: tr1