jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - pip install -r requirements.txt
      - run:
          name: Run django tests
          command: |
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1