version: 2.1
orbs:
  python: circleci/python@1.2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      run:
        - python3 -m venv venv
          . venv/Scripts/activate.bat
          pip install -r requirements.txt
      - run:
          name: Run django tests
          command: |
            python3 manage.py test
      - store_artifacts:
          path: test-results/
          destination: tr1