version: 2.1
orbs:
  python: circleci/python@1.2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Run django tests
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            python3 manage.py test
      - store_artifacts:
          path: test-results/
          destination: tr1

