# Generated by Django 2.0.5 on 2020-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(default=None, max_length=140, verbose_name='Видео'),
        ),
    ]
