# Generated by Django 2.0.5 on 2020-10-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201022_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(default=None, max_length=140, verbose_name='Видео'),
        ),
    ]
